services:
  # PostgreSQL with pgvector extension
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: memuri
      POSTGRES_PASSWORD: memuri
      POSTGRES_DB: memuri
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memuri"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching and as Celery broker
  redis:
    image: redis/redis-stack:latest      
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Milvus for vector storage
  milvus:
    image: milvusdb/milvus:v2.5.10
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio

  # Etcd for Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    command: ["/usr/local/bin/etcd", "--advertise-client-urls=http://127.0.0.1:2379", "--listen-client-urls=http://0.0.0.0:2379", "--data-dir=/etcd"]

  # MinIO for Milvus
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    command: ["minio", "server", "/data"]
    ports:
      - "9000:9000"

  # Celery worker for async tasks
  celery_worker:
    build:
      context: .
    command: 'python -m celery worker -A memuri.workers.celery_app --loglevel=info'
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql://memuri:memuri@postgres:5432/memuri
      - C_FORCE_ROOT=true
      - PYTHONPATH=/app

  # Celery beat for scheduled tasks
  celery_beat:
    build:
      context: .
    command: 'python -m celery beat -A memuri.workers.celery_app --loglevel=info'
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - celery_worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - PYTHONPATH=/app

volumes:
  postgres_data:
  redis_data:
  milvus_data:
  etcd_data:
  minio_data:
